FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o sync-worker ./cmd/sync-worker

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/sync-worker .

COPY migrations ./migrations

RUN useradd -r -s /bin/false appuser

USER appuser

CMD ["./sync-worker"]