FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o api ./cmd/api
RUN CGO_ENABLED=0 GOOS=linux go build -o migrate ./cmd/migrate
RUN CGO_ENABLED=0 GOOS=linux go build -o create-index ./cmd/create-index
RUN CGO_ENABLED=0 GOOS=linux go build -o create-apikey ./cmd/create-apikey
RUN CGO_ENABLED=0 GOOS=linux go build -o reset-apikey ./cmd/reset-apikey

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/api .
COPY --from=builder /app/migrate .
COPY --from=builder /app/create-index .
COPY --from=builder /app/create-apikey .
COPY --from=builder /app/reset-apikey .

COPY migrations ./migrations

RUN useradd -r -s /bin/false appuser

USER appuser

EXPOSE 8080

CMD ["./api"]