services:

  mysql:
    image: mysql:8.4

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: indexer

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  opensearch:
    image: opensearchproject/opensearch:3

    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"

    ports:
      - "9200:9200"
      - "9600:9600"

    volumes:
      - opensearch_data:/usr/share/opensearch/data

volumes:
  mysql_data:
  opensearch_data: