services:

  nginx:
    image: nginx:alpine
    restart: unless-stopped

    depends_on:
      - api

    ports:
      - "80:80"

    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    image: ghcr.io/vinicius05051993/knowledge-hub-api:latest

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - sqlserver
      - opensearch

    ports:
      - "8080:8080"

  sync-worker:
    image: ghcr.io/vinicius05051993/knowledge-hub-worker:latest

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - sqlserver
      - opensearch

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

  opensearch:
    image: opensearchproject/opensearch:3

    restart: unless-stopped

    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"

    ports:
      - "9200:9200"
      - "9600:9600"

    volumes:
      - opensearch_data:/usr/share/opensearch/data

volumes:
  sqlserver_data:
  opensearch_data: