services:

  api:
    image: ghcr.io/vinicius05051993/knowledge-hub:latest

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - mysql
      - opensearch

    ports:
      - "8080:8080"

  sync-worker:
    image: ghcr.io/vinicius05051993/knowledge-hub:latest

    command: ./sync-worker

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - mysql
      - opensearch

  mysql:
    image: mysql:8.4

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - mysql_data:/var/lib/mysql

  opensearch:
    image: opensearchproject/opensearch:3

    restart: unless-stopped

    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"

    volumes:
      - opensearch_data:/usr/share/opensearch/data

volumes:

  mysql_data:

  opensearch_data: